[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"
rust-version = "1.83"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
indoc = "2.0.5"
lazy_static = "1.5.0"
num-format = "0.4.4"
regex = "1.11.1"
